import React from "react";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiDocker,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiGit,
  SiLinux,
  SiPython,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiJupyter,
  SiOpencv,
  SiSolidity,
  SiTelegram,
  SiEthereum,
  SiWeb3Dotjs,
  SiIpfs,
} from "react-icons/si";
import { FaAws, FaBrain, FaCode, FaRobot, FaCube } from "react-icons/fa6";
import { TbCoins, TbContract, TbBrandTelegram, TbDatabase, TbCloudComputing } from "react-icons/tb";

export const TECH_CATEGORIES = [
  { id: "all", label: "All Technologies", icon: "✨" },
  { id: "web-cloud", label: "Web Dev, Cloud & DevOps", icon: "🌐" },
  { id: "ai-ds", label: "Data Science & AI / ML", icon: "🤖" },
  { id: "web3-crypto", label: "Telegram Bots, MiniApps & Web3", icon: "⚡" },
];

export const ALL_TECHNOLOGIES = [
  // ==========================================
  // PILLAR 1: Web Development, Cloud & DevOps
  // ==========================================
  {
    name: "React.js",
    category: "web-cloud",
    categoryLabel: "Frontend Core",
    icon: <SiReact />,
    color: "#61DAFB",
    level: "Advanced",
    description: "Component architecture, hooks, state management & client-side rendering.",
  },
  {
    name: "Next.js",
    category: "web-cloud",
    categoryLabel: "Full-Stack Framework",
    icon: <SiNextdotjs />,
    color: "#FFFFFF",
    level: "Advanced",
    description: "App Router, SSR, SSG, Server Actions & edge deployment.",
  },
  {
    name: "TypeScript",
    category: "web-cloud",
    categoryLabel: "Language",
    icon: <SiTypescript />,
    color: "#3178C6",
    level: "Advanced",
    description: "Type safety, interfaces, generics & enterprise-grade codebase architecture.",
  },
  {
    name: "Docker",
    category: "web-cloud",
    categoryLabel: "DevOps & Containers",
    icon: <SiDocker />,
    color: "#2496ED",
    level: "Intermediate",
    description: "Multi-stage containerization, Docker Compose & reproducible microservices.",
  },
  {
    name: "AWS (Amazon Web Services)",
    category: "web-cloud",
    categoryLabel: "Cloud Computing",
    icon: <FaAws />,
    color: "#FF9900",
    level: "Intermediate",
    description: "EC2 virtual instances, S3 storage, Lambda serverless & CloudFront CDN.",
  },
  {
    name: "Node.js",
    category: "web-cloud",
    categoryLabel: "Backend Runtime",
    icon: <SiNodedotjs />,
    color: "#5FA04E",
    level: "Advanced",
    description: "Asynchronous event-driven I/O, microservices & REST/WebSocket servers.",
  },
  {
    name: "Express.js",
    category: "web-cloud",
    categoryLabel: "Backend API",
    icon: <SiExpress />,
    color: "#E2E8F0",
    level: "Advanced",
    description: "Scalable REST APIs, middleware pipelines & secure auth systems.",
  },
  {
    name: "PostgreSQL",
    category: "web-cloud",
    categoryLabel: "Relational SQL Database",
    icon: <SiPostgresql />,
    color: "#4169E1",
    level: "Intermediate",
    description: "ACID transactions, relational schemas, indexing & complex joins.",
  },
  {
    name: "MongoDB",
    category: "web-cloud",
    categoryLabel: "NoSQL Database",
    icon: <SiMongodb />,
    color: "#47A248",
    level: "Advanced",
    description: "Document models, Mongoose schemas & aggregation pipelines.",
  },
  {
    name: "Redis",
    category: "web-cloud",
    categoryLabel: "In-Memory Cache",
    icon: <SiRedis />,
    color: "#FF4438",
    level: "Intermediate",
    description: "High-speed caching, pub/sub messaging & session store optimization.",
  },
  {
    name: "Tailwind CSS",
    category: "web-cloud",
    categoryLabel: "Design System",
    icon: <SiTailwindcss />,
    color: "#38BDF8",
    level: "Advanced",
    description: "Modern responsive utility styling, dark modes & responsive layouts.",
  },
  {
    name: "JavaScript (ES6+)",
    category: "web-cloud",
    categoryLabel: "Language",
    icon: <SiJavascript />,
    color: "#F7DF1E",
    level: "Advanced",
    description: "Modern JavaScript, event loop, Promises & DOM manipulation.",
  },
  {
    name: "Git & GitHub",
    category: "web-cloud",
    categoryLabel: "Version Control",
    icon: <SiGit />,
    color: "#F05032",
    level: "Advanced",
    description: "Git workflow, branching strategies, code review & CI/CD automation.",
  },
  {
    name: "Linux & Bash",
    category: "web-cloud",
    categoryLabel: "Server Management",
    icon: <SiLinux />,
    color: "#FCC624",
    level: "Intermediate",
    description: "CLI server management, permissions, shell scripts & daemon processes.",
  },
  {
    name: "Three.js / WebGL",
    category: "web-cloud",
    categoryLabel: "3D Creative Graphics",
    icon: <FaCube />,
    color: "#00F0FF",
    level: "Intermediate",
    description: "3D scene composition, shaders, interactive cameras & physics.",
  },

  // ==========================================
  // PILLAR 2: Beginner Data Science & AI / ML
  // ==========================================
  {
    name: "Python",
    category: "ai-ds",
    categoryLabel: "Core Language",
    icon: <SiPython />,
    color: "#3776AB",
    level: "Advanced",
    description: "Data analysis scripting, backend automation & ML pipeline engineering.",
  },
  {
    name: "PyTorch",
    category: "ai-ds",
    categoryLabel: "Deep Learning",
    icon: <SiPytorch />,
    color: "#EE4C2C",
    level: "Beginner-Inter",
    description: "Tensors, neural network layers, autograd & model training loops.",
  },
  {
    name: "TensorFlow",
    category: "ai-ds",
    categoryLabel: "Machine Learning",
    icon: <SiTensorflow />,
    color: "#FF6F00",
    level: "Beginner",
    description: "Keras functional models, classification & computational graphs.",
  },
  {
    name: "Scikit-Learn",
    category: "ai-ds",
    categoryLabel: "Classical ML",
    icon: <SiScikitlearn />,
    color: "#F7931E",
    level: "Intermediate",
    description: "Regression, Random Forests, SVMs, clustering & feature engineering.",
  },
  {
    name: "Pandas",
    category: "ai-ds",
    categoryLabel: "Data Manipulation",
    icon: <SiPandas />,
    color: "#150458",
    level: "Advanced",
    description: "DataFrames, data cleaning, aggregation, time series & CSV/JSON ETL.",
  },
  {
    name: "NumPy",
    category: "ai-ds",
    categoryLabel: "Numerical Math",
    icon: <SiNumpy />,
    color: "#013243",
    level: "Advanced",
    description: "N-dimensional array operations, matrix linear algebra & vectorization.",
  },
  {
    name: "Jupyter Notebooks",
    category: "ai-ds",
    categoryLabel: "Interactive Data Lab",
    icon: <SiJupyter />,
    color: "#F37626",
    level: "Advanced",
    description: "Exploratory data analysis, rapid prototyping & visual reporting.",
  },
  {
    name: "OpenCV (Computer Vision)",
    category: "ai-ds",
    categoryLabel: "Vision Processing",
    icon: <SiOpencv />,
    color: "#5C3EE8",
    level: "Beginner",
    description: "Image processing, edge detection, filtering & camera feeds.",
  },
  {
    name: "LLM & OpenAI APIs",
    category: "ai-ds",
    categoryLabel: "Generative AI",
    icon: <FaBrain />,
    color: "#10A37F",
    level: "Intermediate",
    description: "GPT integrations, prompt engineering, embeddings & RAG pipelines.",
  },

  // ==========================================
  // PILLAR 3: Telegram Bot, MiniApps & Web3
  // ==========================================
  {
    name: "Telegram Bot API",
    category: "web3-crypto",
    categoryLabel: "Bot Automation",
    icon: <SiTelegram />,
    color: "#26A5E4",
    level: "Advanced",
    description: "Custom Telegram bots, inline commands, webhook handlers & user flows.",
  },
  {
    name: "Telegram Mini Apps (TMA)",
    category: "web3-crypto",
    categoryLabel: "MiniApp Ecosystem",
    icon: <TbBrandTelegram />,
    color: "#0088CC",
    level: "Advanced",
    description: "Full web apps inside Telegram, Telegram WebApp SDK & viewport handling.",
  },
  {
    name: "TON Blockchain",
    category: "web3-crypto",
    categoryLabel: "TON Ecosystem",
    icon: <TbCoins />,
    color: "#0098EA",
    level: "Intermediate",
    description: "The Open Network integrations, TON Connect wallet logins & Jettons.",
  },
  {
    name: "Solidity",
    category: "web3-crypto",
    categoryLabel: "Smart Contracts",
    icon: <SiSolidity />,
    color: "#AA67F2",
    level: "Intermediate",
    description: "EVM smart contract authoring, ERC-20 / ERC-721 tokens & gas optimization.",
  },
  {
    name: "Smart Contract Testing",
    category: "web3-crypto",
    categoryLabel: "Contract Architecture",
    icon: <TbContract />,
    color: "#34D399",
    level: "Intermediate",
    description: "Unit testing, state verification, security auditing & deployment scripts.",
  },
  {
    name: "Ethereum & EVM",
    category: "web3-crypto",
    categoryLabel: "Blockchain Network",
    icon: <SiEthereum />,
    color: "#627EEA",
    level: "Intermediate",
    description: "Ethereum virtual machine architecture, RPC providers & testnets.",
  },
  {
    name: "Ethers.js / Viem",
    category: "web3-crypto",
    categoryLabel: "Web3 SDK",
    icon: <SiWeb3Dotjs />,
    color: "#3B82F6",
    level: "Intermediate",
    description: "Contract interaction, transaction signing, event listeners & ABI parsing.",
  },
  {
    name: "Hardhat",
    category: "web3-crypto",
    categoryLabel: "Dev Environment",
    icon: <FaCode />,
    color: "#FFF100",
    level: "Intermediate",
    description: "Local blockchain node, contract compilation, testing & deployment.",
  },
  {
    name: "IPFS & Pinata",
    category: "web3-crypto",
    categoryLabel: "Decentralized Storage",
    icon: <SiIpfs />,
    color: "#65C2CB",
    level: "Intermediate",
    description: "Decentralized file storage, content addressing (CIDs) & NFT metadata.",
  },
];

// Row 1: Full-Stack Web Development Essentials (Left -> Right)
export const ROW_1_WEB = [
  ALL_TECHNOLOGIES.find((t) => t.name === "React.js"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Next.js"),
  ALL_TECHNOLOGIES.find((t) => t.name === "TypeScript"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Node.js"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Express.js"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Tailwind CSS"),
  ALL_TECHNOLOGIES.find((t) => t.name === "JavaScript (ES6+)"),
  ALL_TECHNOLOGIES.find((t) => t.name === "PostgreSQL"),
  ALL_TECHNOLOGIES.find((t) => t.name === "MongoDB"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Redis"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Three.js / WebGL"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Git & GitHub"),
].filter(Boolean);

// Row 2: DevOps, Cloud & Machine Learning / Data Science (Right -> Left)
export const ROW_2_AI_ML_DEVOPS = [
  ALL_TECHNOLOGIES.find((t) => t.name === "Docker"),
  ALL_TECHNOLOGIES.find((t) => t.name === "AWS (Amazon Web Services)"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Python"),
  ALL_TECHNOLOGIES.find((t) => t.name === "PyTorch"),
  ALL_TECHNOLOGIES.find((t) => t.name === "TensorFlow"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Scikit-Learn"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Pandas"),
  ALL_TECHNOLOGIES.find((t) => t.name === "NumPy"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Jupyter Notebooks"),
  ALL_TECHNOLOGIES.find((t) => t.name === "OpenCV (Computer Vision)"),
  ALL_TECHNOLOGIES.find((t) => t.name === "LLM & OpenAI APIs"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Linux & Bash"),
].filter(Boolean);

// Row 3: Telegram Bots, MiniApps, Web3 & Smart Contracts (Left -> Right)
export const ROW_3_WEB3_TELEGRAM = [
  ALL_TECHNOLOGIES.find((t) => t.name === "Telegram Bot API"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Telegram Mini Apps (TMA)"),
  ALL_TECHNOLOGIES.find((t) => t.name === "TON Blockchain"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Solidity"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Smart Contract Testing"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Ethereum & EVM"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Ethers.js / Viem"),
  ALL_TECHNOLOGIES.find((t) => t.name === "Hardhat"),
  ALL_TECHNOLOGIES.find((t) => t.name === "IPFS & Pinata"),
].filter(Boolean);
